### ISSUE TITLE
GeoLite2 databases cause panics

### ISSUE THREAD

**Issue by chaimleib** [maxmind/mmdbverify#2]
To reproduce:
```
wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
tar -xf GeoLite2-City.tar.gz

go get github.com/maxmind/mmdbverify
mmdbverify -file GeoLite2-City_*/GeoLite2-City.mmdb
```

Result:
```
unexpected fault address 0x77dd000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x77dd000 pc=0x10c37bb]

goroutine 1 [running]:
runtime.throw(0x1104937, 0x5)
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/panic.go:617 +0x72 fp=0xc0001b3588 sp=0xc0001b3558 pc=0x102a462
runtime.sigpanic()
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/signal_unix.go:397 +0x401 fp=0xc0001b35b8 sp=0xc0001b3588 pc=0x103cf31
github.com/oschwald/maxminddb-golang.(*decoder).decodeUint(0xc0001b3de8, 0x2, 0x162f0, 0xc0001b3690, 0x10791d1, 0x10e2480, 0x0)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/decoder.go:646 +0x4b fp=0xc0001b35c8 sp=0xc0001b35b8 pc=0x10c37bb
github.com/oschwald/maxminddb-golang.(*decoder).unmarshalUint(0xc0001b3de8, 0x2, 0x162f0, 0x10e2480, 0xc0004619f0, 0x194, 0x10, 0x2, 0x162f0, 0x0)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/decoder.go:387 +0x72 fp=0xc0001b36a8 sp=0xc0001b35c8 pc=0x10c1b32
github.com/oschwald/maxminddb-golang.(*decoder).decodeFromType(0xc0001b3de8, 0x5, 0x2, 0x162f0, 0x10d4ae0, 0xc0004619f0, 0x16, 0x3, 0xc0004619f0, 0xc0001b37a0, ...)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/decoder.go:146 +0x2c1 fp=0xc0001b3728 sp=0xc0001b36a8 pc=0x10bec01
github.com/oschwald/maxminddb-golang.(*decoder).decode(0xc0001b3de8, 0x162ef, 0x10d4ae0, 0xc0004619f0, 0x16, 0x2, 0x0, 0x0, 0x30)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/decoder.go:54 +0xec fp=0xc0001b37b0 sp=0xc0001b3728 pc=0x10be31c
github.com/oschwald/maxminddb-golang.(*decoder).decodeMap(0xc0001b3de8, 0x4, 0x162ef, 0x10e2b40, 0xc0000978c0, 0x15, 0x2, 0x1004, 0x10e2480, 0xc0004617d0)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/decoder.go:491 +0x23f fp=0xc0001b3868 sp=0xc0001b37b0 pc=0x10c28ff
github.com/oschwald/maxminddb-golang.(*decoder).unmarshalMap(0xc0001b3de8, 0x4, 0x162ed, 0x10e2480, 0xc0004619e0, 0x194, 0x2, 0x4, 0x162ed, 0x0)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/decoder.go:324 +0x3d3 fp=0xc0001b3970 sp=0xc0001b3868 pc=0x10c0fa3
github.com/oschwald/maxminddb-golang.(*decoder).decodeFromType(0xc0001b3de8, 0x7, 0x4, 0x162ed, 0x10d4ae0, 0xc0004619e0, 0x16, 0x2, 0xc0004619e0, 0xc0001b3a68, ...)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/decoder.go:123 +0x57e fp=0xc0001b39f0 sp=0xc0001b3970 pc=0x10beebe
github.com/oschwald/maxminddb-golang.(*decoder).decode(0xc0001b3de8, 0x162ec, 0x10d4ae0, 0xc0004619e0, 0x16, 0x1, 0x0, 0x0, 0x194)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/decoder.go:54 +0xec fp=0xc0001b3a78 sp=0xc0001b39f0 pc=0x10be31c
github.com/oschwald/maxminddb-golang.(*decoder).decodeMap(0xc0001b3de8, 0x7, 0x162ec, 0x10e2b40, 0xc000097770, 0x15, 0x1, 0x162db, 0x0, 0x0)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/decoder.go:491 +0x23f fp=0xc0001b3b30 sp=0xc0001b3a78 pc=0x10c28ff
github.com/oschwald/maxminddb-golang.(*decoder).unmarshalMap(0xc0001b3de8, 0x7, 0x162dc, 0x10e2480, 0xc0004613d0, 0x194, 0x1, 0x7, 0x162dc, 0x0)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/decoder.go:324 +0x3d3 fp=0xc0001b3c38 sp=0xc0001b3b30 pc=0x10c0fa3
github.com/oschwald/maxminddb-golang.(*decoder).decodeFromType(0xc0001b3de8, 0x7, 0x7, 0x162dc, 0x10d4ae0, 0xc0004613d0, 0x16, 0x1, 0xc001392a48, 0xc0001b3d30, ...)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/decoder.go:123 +0x57e fp=0xc0001b3cb8 sp=0xc0001b3c38 pc=0x10beebe
github.com/oschwald/maxminddb-golang.(*decoder).decode(0xc0001b3de8, 0x162db, 0x10d4ae0, 0xc0004613d0, 0x16, 0x0, 0x162db, 0x0, 0x0)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/decoder.go:54 +0xec fp=0xc0001b3d40 sp=0xc0001b3cb8 pc=0x10be31c
github.com/oschwald/maxminddb-golang.(*verifier).verifyDataSection(0xc000056f00, 0xc0000ce060, 0x0, 0x0)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/verifier.go:137 +0x18d fp=0xc0001b3eb0 sp=0xc0001b3d40 pc=0x10c63dd
github.com/oschwald/maxminddb-golang.(*verifier).verifyDatabase(0xc000056f00, 0x0, 0x0)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/verifier.go:94 +0x91 fp=0xc0001b3ee8 sp=0xc0001b3eb0 pc=0x10c5e51
github.com/oschwald/maxminddb-golang.(*Reader).Verify(0xc0000e4000, 0x29, 0xc0000e4000)
	/Users/chalbert/go/src/github.com/oschwald/maxminddb-golang/verifier.go:18 +0x6f fp=0xc0001b3f18 sp=0xc0001b3ee8 pc=0x10c545f
main.main()
	/Users/chalbert/go/src/github.com/maxmind/mmdbverify/main.go:28 +0x197 fp=0xc0001b3f98 sp=0xc0001b3f18 pc=0x10c6ff7
runtime.main()
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/proc.go:200 +0x20c fp=0xc0001b3fe0 sp=0xc0001b3f98 pc=0x102bdbc
runtime.goexit()
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0001b3fe8 sp=0xc0001b3fe0 pc=0x10537b1
```

**Comment by oschwald** [comment]
What version of Go are you running?

**Comment by chaimleib** [comment]
1.12.4 at the time I produced that result. We’re constantly testing locally using the latest version available from homebrew, as well as GAE go 1.9.

**Comment by oschwald** [comment]
I believe this is the same issue as https://github.com/oschwald/maxminddb-golang/issues/55. Would you be able to try the version 1.3.1 of `github.com/oschwald/maxminddb-golang`?

**Comment by oschwald** [comment]
I am closing this as I believe that it is fixed.

**Comment by chaimleib** [comment]
Thanks! I just tried it today, and it seems to work!
